export default {
  UPDATE_EDUCATION_DETAIL: 'UPDATE_EDUCATION_DETAIL',
  UPDATE_EDUCATION_DETAIL_COUNT: 'UPDATE_EDUCATION_DETAIL_COUNT',
  DELETE_EDUCATION_DETAIL_COUNT: 'DELETE_EDUCATION_DETAIL_COUNT'
}
