export default {
  UPDATE_PROFESSION_DETAIL: 'UPDATE_PROFESSION_DETAIL',
  UPDATE_PROFESSION_DETAIL_COUNT: 'UPDATE_PROFESSION_DETAIL_COUNT',
  DELETE_PROFESSION_DETAIL_COUNT: 'DELETE_PROFESSION_DETAIL_COUNT'
}
